# Generated by Django 4.0.6 on 2022-08-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_movie_director'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Directors',
            new_name='Director',
        ),
    ]
